baseURL = "https://docs.leakix.net/"
title = "LeakIX Docs"
enableRobotsTXT = true
# this example loads the theme as hugo module
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
theme = ["github.com/LeakIX/hugo-leakix-dark"]
# theme = "hugo-leakix-dark"
enableGitInfo = true

# disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "RSS","JSON"]
